name: Bug Report
description: Report a bug or problem found in existing functionality
title: "fix: "
labels: ["type:fix", "severity:medium"]
type: bug
assignees: []

body:
  - type: markdown
    attributes:
      value: "### Report a Bug\nPlease verify that the issue has not already been reported."
  
  - type: markdown
    id: severity
    value: "### Severity\nSet the severity of this bug. Select the appropriate severity level from the Labels section on the right (cogwheel)."

  - type: dropdown
    id: service
    attributes:
      label: "Service"
      description: "Select the service where the issue was encountered."
      options:
        - cloud.io
        - db population tool
        - db search
        - transpecr

  - type: textarea
    id: overview1
    attributes:
      label: "Version"
      description: "The version number of the service where the issue was encountered."
      placeholder: "MAJOR.MINOR.REVISION"

  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "Provide a short description of the issue. Please check if the issue has not already been reported."
      placeholder: "Briefly describe the issue"

  - type: markdown
    attributes:
      value: "### Steps to reproduce\nList the exact steps to reproduce the issue."

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List each step in detail."
      value: "- Step 1\n- Step 2"

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What was the expected behavior?"
      placeholder: "Describe the expected outcome"

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes"
      description: "Add any related issues, resources, diagrams, or references."
      placeholder: "Include additional notes here"